### ISSUE TITLE
tests for smartcab/agent.py

### ISSUE THREAD

**Issue by stopachka** [udacity/machine-learning#250]
When working on smartcab, it's difficult to figure out when my smartcab is having trouble because of the learning rate I am working with, or whether I messed up the implementation of some other function. 

it would be great if we had some quick tests for those functions

**Comment by consideRatio** [comment]
The project currently have misleading bugs in the rewards, it also is setup quite complex which makes the learning rate choice a very complex matter theoretically.

I'll write an issue and try remember referencing the issue here later...

For the issues with the rewards, see my pull request: https://github.com/udacity/machine-learning/pull/268
